### ISSUE TITLE
Add test_examples.sh that ensures example scripts work

### ISSUE THREAD

**Issue by keiohta** [keiohta/tf2rl#38]

**Comment by keiohta** [comment]
Add `test_run_examples.sh` but does not reflect to build status, i.e., the build status is green even if this script fails. Is that impossible to reflect the result of this script to build status?
https://github.com/keiohta/tf2rl/blob/master/test_run_examples.sh

**Comment by yamada-github-account** [comment]
``` diff
- bash test_run_example.sh
+ ./test_run_example.sh
```

Additionally, you might need to make the script file executable by `chmod`

Since you run the script inside new subprocess `bash`, even though the script fails, the `bash` subprocess exits "correctly" and its exit code becomes `0`.

---

Your shebang (#!/bin/bash -eu) seems to be ignored. (Your Travis did not stop initial error.)

I simply guess that you explicitly specify `bash` then shebang is ignored.

If you want the script always stop whenever an error happen, `set -eu` is preferable instead of specifying at shebang.
