### ISSUE TITLE
cpprb will break its api in version 8

### ISSUE THREAD

**Issue by yamada-github-account** [keiohta/tf2rl#43]
A depending library cpprb is scheduled to break its api in version 8.
(`ReplayBuffer`s in `cpprb` namespaces are replaced with those in `cpprb.experimental`, filnally.)

To prepare migration, the current version of tf2rl is recommended to ensure to use version 7 by specifying in setup.py

**Comment by keiohta** [comment]
Thank you for this issue and the related PR!
I close this issue because I merged your PR.

I would like you to let me know once your latest version is fixed, and ready to use `NStepReplayBuffer` and `NStepPrioritizedReplayBuffer`. I'm really looking forward to trying your super-fast `cpprb` implementation!
