### ISSUE TITLE
Installing errors on Apple macOS

### ISSUE THREAD

**Issue by janbolle** [keiohta/tf2rl#75]
If you run into errors installing `cpprb` this will solve your problem:

"Just" install gcc, llvm with brew

```bash
brew install gcc llvm
```

Then tell your system to use the newly installed gcc, and not the apple-xcode one by running

```bash
source gcc_export
```

Then clone repository

```bash
git clone https://github.com/keiohta/tf2rl
```
and switch to directory and install with
```bash
pip install -e .
```

#### gcc_export

```bash
export CC=/usr/local/bin/gcc-9
export CXX=/usr/local/bin/g++-9
export CPP=/usr/local/bin/cpp-9
export LD=/usr/local/bin/gcc-9
alias c++=/usr/local/bin/c++-9
alias g++=/usr/local/bin/g++-9
alias gcc=/usr/local/bin/gcc-9
alias cpp=/usr/local/bin/cpp-9
alias ld=/usr/local/bin/gcc-9
alias cc=/usr/local/bin/gcc-9
```

**Comment by yamada-github-account** [comment]
@janbolle 
Thank you for your contribution.

I'm owner of `cpprb`

I have acknowledged the installation problem caused by clang (libc++).
Actually, I did similar way on my macOS in the early development stage. 
(Now using docker)

clang has not implemented array specialization of `std::shared_ptr` which is a part of C++17.
http://libcxx.llvm.org/cxx1z_status.html (P0414R2 etc.)

This is the major obstacle against binary distribution for macOS at PyPI.

Anyway, I will improve `cpprb` README (and maybe @keiohta will put navigation link at somewhere in `tf2rl`).
If possible, I will make `cpprb` compilable on macOS with "native" development tool chain, too.

P.S.
@keiohta and I are close friend, however, in general, `tf2rl` and `cpprb` are developed separately.
So it would be greater, if you could post issues/requests at https://gitlab.com/ymd_h/cpprb in the next time, in stead of here.
